"""empty message

Revision ID: a1e1d4b8faa5
Revises: d4e42bcf9890
Create Date: 2017-03-13 01:08:48.387762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e1d4b8faa5'
down_revision = 'd4e42bcf9890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('date_created', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'date_created')
    # ### end Alembic commands ###
