"""empty message

Revision ID: d4e42bcf9890
Revises: cfcec18e6e6f
Create Date: 2017-03-13 00:57:34.070714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e42bcf9890'
down_revision = 'cfcec18e6e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('biography', sa.String(length=255), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('image', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.drop_column('user_profile', 'image')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'biography')
    op.drop_column('user_profile', 'age')
    # ### end Alembic commands ###
